import type { SkillRecord } from "./types";

export const CATALOG_TOTAL = 179054;
export const CATALOG_SOURCE = "ClaudSkills daily mirror";
export const CATALOG_SOURCE_URL = "https://huggingface.co/datasets/claudskills/skills";
export const SKILLS_SH_SOURCE_URL = "https://skills.sh";

export const FALLBACK_SKILLS: SkillRecord[] = [
  {
    id: "anthropics/skills/frontend-design",
    slug: "frontend-design",
    name: "frontend-design",
    description: "Create distinctive, production-grade interfaces with a clear visual point of view.",
    category: "design-creative",
    subcategory: "frontend",
    tags: ["design", "frontend", "ui"],
    author: "anthropics",
    authorUrl: "https://github.com/anthropics",
    sourceUrl: "https://github.com/anthropics/skills",
    catalogUrl: "https://skills.sh/anthropics/skills/frontend-design",
    license: "Source available",
    lastmod: "2026-08-11",
    installs: 917900,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
  {
    id: "vercel-labs/agent-skills/vercel-react-best-practices",
    slug: "vercel-react-best-practices",
    name: "vercel-react-best-practices",
    description: "Apply practical React and Next.js performance patterns while building and reviewing interfaces.",
    category: "engineering",
    subcategory: "frontend",
    tags: ["react", "nextjs", "performance"],
    author: "vercel-labs",
    authorUrl: "https://github.com/vercel-labs",
    sourceUrl: "https://github.com/vercel-labs/agent-skills",
    catalogUrl: "https://skills.sh/vercel-labs/agent-skills/vercel-react-best-practices",
    license: "MIT",
    lastmod: "2026-08-11",
    installs: 740100,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
  {
    id: "mattpocock/skills/diagnosing-bugs",
    slug: "diagnosing-bugs",
    name: "diagnosing-bugs",
    description: "Turn an ambiguous defect into a reproducible hypothesis, a narrow experiment, and a verified fix.",
    category: "engineering",
    subcategory: "debugging",
    tags: ["debugging", "testing", "diagnosis"],
    author: "mattpocock",
    authorUrl: "https://github.com/mattpocock",
    sourceUrl: "https://github.com/mattpocock/skills",
    catalogUrl: "https://skills.sh/mattpocock/skills/diagnosing-bugs",
    license: "MIT",
    lastmod: "2026-08-11",
    installs: 656800,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
  {
    id: "anthropics/skills/skill-creator",
    slug: "skill-creator",
    name: "skill-creator",
    description: "Author a portable SKILL.md with strong trigger language, focused instructions, and useful resources.",
    category: "agents",
    subcategory: "authoring",
    tags: ["agents", "skills", "authoring"],
    author: "anthropics",
    authorUrl: "https://github.com/anthropics",
    sourceUrl: "https://github.com/anthropics/skills",
    catalogUrl: "https://skills.sh/anthropics/skills/skill-creator",
    license: "Source available",
    lastmod: "2026-08-11",
    installs: 389500,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
  {
    id: "vercel-labs/skills/find-skills",
    slug: "find-skills",
    name: "find-skills",
    description: "Find the right reusable capability before an agent starts improvising a workflow from scratch.",
    category: "agents",
    subcategory: "discovery",
    tags: ["agents", "mcp", "discovery"],
    author: "vercel-labs",
    authorUrl: "https://github.com/vercel-labs",
    sourceUrl: "https://github.com/vercel-labs/skills",
    catalogUrl: "https://skills.sh/vercel-labs/skills/find-skills",
    license: "MIT",
    lastmod: "2026-08-11",
    installs: 3539000,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
  {
    id: "obra/superpowers/brainstorming",
    slug: "brainstorming",
    name: "brainstorming",
    description: "Explore a problem space, compare directions, and turn a vague request into a buildable decision.",
    category: "product",
    subcategory: "planning",
    tags: ["planning", "product", "ideation"],
    author: "obra",
    authorUrl: "https://github.com/obra",
    sourceUrl: "https://github.com/obra/superpowers",
    catalogUrl: "https://skills.sh/obra/superpowers/brainstorming",
    license: "MIT",
    lastmod: "2026-08-11",
    installs: 374600,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
  {
    id: "supabase/agent-skills/supabase-postgres-best-practices",
    slug: "supabase-postgres-best-practices",
    name: "supabase-postgres-best-practices",
    description: "Design and review Postgres-backed applications with safer queries, indexes, and operational defaults.",
    category: "data",
    subcategory: "database",
    tags: ["postgres", "supabase", "database"],
    author: "supabase",
    authorUrl: "https://github.com/supabase",
    sourceUrl: "https://github.com/supabase/agent-skills",
    catalogUrl: "https://skills.sh/supabase/agent-skills/supabase-postgres-best-practices",
    license: "Apache-2.0",
    lastmod: "2026-08-11",
    installs: 414700,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
  {
    id: "getsentry/skills/skill-scanner",
    slug: "skill-scanner",
    name: "skill-scanner",
    description: "Inspect a skill package for unsafe instructions, suspicious capabilities, and supply-chain red flags.",
    category: "security",
    subcategory: "review",
    tags: ["security", "audit", "skills"],
    author: "getsentry",
    authorUrl: "https://github.com/getsentry",
    sourceUrl: "https://github.com/getsentry/skills",
    catalogUrl: "https://skills.sh/getsentry/skills/skill-scanner",
    license: "MIT",
    lastmod: "2026-08-11",
    installs: 3089,
    sourceKind: "sealed-fallback",
    live: false,
    compatibility: [],
  },
];

export function cloneFallbackSkills(): SkillRecord[] {
  return FALLBACK_SKILLS.map((skill) => ({ ...skill, tags: [...skill.tags], compatibility: [] }));
}
