import { ArrowRight, Boxes, CheckCircle2, Code2, Cpu, Search, ShieldCheck, Terminal, Workflow } from "lucide-react";
import Link from "next/link";
import { getCatalog } from "@/lib/catalog";
import { MotionReveal } from "@/components/motion-reveal";
import { SignalBoard } from "@/components/signal-board";
import { SourceBadge } from "@/components/source-badge";
import { SkillCopyRail } from "@/components/copy-button";
import { FeatureTile, Metric, MiniFlow, SectionLabel } from "@/components/ui";

export default async function Home() {
  const catalog = await getCatalog({ limit: 48 });
  return <div className="home-page">
    <section className="hero shell">
      <div className="hero-copy"><MotionReveal><SectionLabel tone="orange">field note / 07—26</SectionLabel><h1>Route one skill<br /><em>everywhere.</em></h1><p className="hero-lede">Skill Relay turns the public agent-skill sprawl into a readable compatibility lab. Find a real signal, score the fit, then persist a native packet for every runtime your team uses.</p><div className="hero-actions"><Link href="/explore" className="btn-primary">Open the index <ArrowRight size={17} /></Link><Link href="/agent" className="btn-secondary"><Terminal size={16} /> Call the agent API</Link></div><div className="hero-proof"><span><CheckCircle2 size={15} /> 179,054 public records</span><span><CheckCircle2 size={15} /> 7 target harnesses</span><span><CheckCircle2 size={15} /> SHA-384 audit trail</span></div></MotionReveal></div>
      <MotionReveal delay={0.12}><SignalBoard /></MotionReveal>
    </section>
    <section className="metric-strip shell"><Metric value="179k+" label="public records" detail="ClaudSkills mirror" tone="blue" /><Metric value="7" label="harnesses" detail="native target paths" tone="orange" /><Metric value="1" label="shared engine" detail="UI · REST · MCP" tone="lime" /><Metric value="0" label="required keys" detail="core experience" tone="ink" /></section>
    <section className="shell editorial-section"><div className="section-intro"><SectionLabel tone="blue">the shift</SectionLabel><h2>A directory tells you what exists.<br /><span>Skill Relay tells you what to do next.</span></h2><p>Most skill catalogs stop at a search result. Relay adds the missing middle: a task-shaped score, a concrete install path, and a persisted pack that your humans and agents can share.</p></div><div className="feature-grid"><FeatureTile icon={Search} title="Find the signal" body="Search a real public index and keep source provenance beside every result." tone="blue" /><FeatureTile icon={Cpu} title="Score the fit" body="A deterministic engine explains task alignment, freshness, adoption, risk, and harness coverage." tone="orange" /><FeatureTile icon={Workflow} title="Relay the packet" body="Turn one capability into native paths for Claude Code, Codex, OpenClaw, Hermes, OpenCode, Gemini, and Cursor." tone="lime" /><FeatureTile icon={ShieldCheck} title="Replay the proof" body="Every mutation is appended to a SHA-384 seal chain that can be replayed from the API." tone="ink" /></div></section>
    <section className="shell flow-section"><div className="flow-panel paper-card"><div className="flow-copy"><SectionLabel tone="orange">the relay loop</SectionLabel><h2>From public signal<br />to shared capability.</h2><p>The same boundary serves the browser, curl, and an agent calling MCP. No second ranking implementation. No hidden local-only state.</p><MiniFlow /><Link href="/explore" className="text-link">See the live index <ArrowRight size={15} /></Link></div><div className="flow-diagram"><div className="diagram-rail rail-blue"><span>01</span><b>observe</b><small>skills.sh + mirror</small></div><div className="diagram-line" /><div className="diagram-rail rail-orange"><span>02</span><b>explain</b><small>score factors</small></div><div className="diagram-line" /><div className="diagram-rail rail-lime"><span>03</span><b>relay</b><small>persisted pack</small></div><div className="diagram-stamp"><Code2 size={19} /><span>same engine<br />every surface</span></div></div></div></section>
     <section className="shell featured-section"><div className="section-heading"><div><SectionLabel tone="blue">fresh packets</SectionLabel><h2>Start with a signal.</h2></div><Link href="/explore" className="btn-secondary">Browse all <ArrowRight size={16} /></Link></div><div className="featured-grid">{catalog.items.slice(0, 3).map((skill, index) => <article className="featured-card paper-card" key={skill.id}><Link href={`/skill/${skill.slug}`} className="featured-card-link"><div className="featured-index">0{index + 1}</div><div className="featured-top"><SourceBadge live={skill.live} label={skill.sourceKind === "claudskills" ? "ClaudSkills" : skill.sourceKind === "skills.sh" ? "skills.sh" : "sealed fallback"} /><span>{skill.category}</span></div><h3>{skill.name}</h3><p>{skill.description}</p><div className="featured-foot"><span>{skill.author || "community"}</span><ArrowRight size={16} /></div></Link><SkillCopyRail skill={skill} compact /></article>)}</div></section>
    <section className="shell closing-cta"><div className="closing-mark"><Boxes size={24} /></div><div><SectionLabel tone="lime">make the next move</SectionLabel><h2>Give your agents<br /><em>better packets.</em></h2></div><div><p>Open the explorer, save a relay, or let an agent do it through the same audited API.</p><Link href="/packs" className="btn-primary">Open relay workspace <ArrowRight size={17} /></Link></div></section>
    <div className="home-footnote shell"><span>Source note</span><p>Catalog totals are public dataset observations, not synthetic filler. Live search can fall back to sealed records when upstream services are unavailable.</p><Link href="/api/catalog" className="text-link">Inspect feed <ArrowRight size={14} /></Link></div>
  </div>;
}
